/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package igu;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author rafae
 */
public class PanelPromociones extends javax.swing.JPanel {
    private Connection conexion;
    private String nivel;
    private String modo;
    /**
     * Creates new form PanelPromociones
     */
    public PanelPromociones(Connection conexion, String nivel) {
        initComponents();
        this.conexion=conexion;
        this.nivel=nivel;
         habilitarCampos(false);
        
    }
    private void limpiarCampos() {
        txtId.setText("");
        txtTipo.setText("");
        txtDescripcion.setText("");
        txtCondicion.setText("");
       
    }

    private void habilitarCampos(boolean habilitar) {
        txtId.setEditable(habilitar);
        txtTipo.setEnabled(habilitar);
        txtDescripcion.setEnabled(habilitar);
        txtCondicion.setEnabled(habilitar);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        txtTipo = new javax.swing.JTextField();
        txtCondicion = new javax.swing.JTextField();
        btnNuevo = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnGrabar = new javax.swing.JButton();
        btnVerPromos = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("BIENVENIDO A LA GESTION DE PROMCIONES");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Id");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Descripcion");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Tipo");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Condicion de horas");

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        txtCondicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCondicionActionPerformed(evt);
            }
        });

        btnNuevo.setText("nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnBuscar.setText("buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnEditar.setText("editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setText("eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnGrabar.setText("grabar");
        btnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarActionPerformed(evt);
            }
        });

        btnVerPromos.setText("ver promociones");
        btnVerPromos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerPromosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtCondicion, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(62, 62, 62)
                                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnGrabar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(btnVerPromos, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCondicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo)
                    .addComponent(btnBuscar)
                    .addComponent(btnEditar)
                    .addComponent(btnEliminar)
                    .addComponent(btnGrabar))
                .addGap(72, 72, 72)
                .addComponent(btnVerPromos)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 500));
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void txtCondicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCondicionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCondicionActionPerformed

    private void btnVerPromosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerPromosActionPerformed
       VentanaPromociones v= new VentanaPromociones(conexion);
       v.setVisible(true);
       v.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnVerPromosActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
       if(nivel.equalsIgnoreCase("administrador")){
          txtId.setEnabled(false);
       limpiarCampos();
       modo="nuevo";
        habilitarCampos(true);
      }else{
          JOptionPane.showMessageDialog(null, "opcion solo para administradores");
      }
    }//GEN-LAST:event_btnNuevoActionPerformed
    
    private void buscarPromo(String idBuscar) {
        if (idBuscar == null || idBuscar.trim().isEmpty()) {
            return;
        }

        try {
            String sql = "SELECT * FROM Promocion WHERE idPromocion = ?";
            PreparedStatement ps = conexion.prepareStatement(sql);
            ps.setString(1, idBuscar.trim());
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                txtId.setText(rs.getString("idPromocion"));
                txtDescripcion.setText(rs.getString("descripcion"));
                txtTipo.setText(rs.getString("tipo"));
                txtCondicion.setText(rs.getString("condicionHoras"));
                habilitarCampos(false);
               

                JOptionPane.showMessageDialog(this, "promocion encontrado. Ahora puede editarlo.");
            } else {
                JOptionPane.showMessageDialog(this, "No se encontró la promocion con ese ID.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al buscar promocion: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
       String promoBuscada = javax.swing.JOptionPane.showInputDialog(this, "Ingrese el ID de la promocion a buscar (ej: P001)");
        if (promoBuscada != null) {
            buscarPromo(promoBuscada.trim());
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if (nivel.equalsIgnoreCase("administrador")) {
            habilitarCampos(true);
            txtId.setEnabled(false);
            modo = "edicion";
        } else {
            JOptionPane.showMessageDialog(null, "opcion solo para administradores");
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (nivel.equalsIgnoreCase("administrador")) {

            String idEliminar = JOptionPane.showInputDialog(this, "Ingrese el ID de la promocion a eliminar (ej: P001):");

            // Validar entrada
            if (idEliminar == null || idEliminar.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Debe ingresar un ID de recurso válido.", "Advertencia", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Confirmación
            int confirmar = JOptionPane.showConfirmDialog(this,
                    "¿Está seguro que desea eliminar la promocion con ID " + idEliminar + "?",
                    "Confirmar eliminación",
                    JOptionPane.YES_NO_OPTION);

            if (confirmar != JOptionPane.YES_OPTION) {
                return; // usuario canceló
            }

            try {
                // Verificar si existe el recurso antes de eliminarlo
                String sqlCheck = "SELECT COUNT(*) FROM Promocion WHERE idPromocion = ?";
                PreparedStatement psCheck = conexion.prepareStatement(sqlCheck);
                psCheck.setString(1, idEliminar.trim());
                ResultSet rs = psCheck.executeQuery();
                rs.next();
                int count = rs.getInt(1);

                if (count == 0) {
                    JOptionPane.showMessageDialog(this, "No existe ninguna Promocion con el ID especificado.", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                // Eliminar registro
                String sqlDelete = "DELETE FROM Promocion WHERE idPromocion = ?";
                PreparedStatement psDelete = conexion.prepareStatement(sqlDelete);
                psDelete.setString(1, idEliminar.trim());
                int filas = psDelete.executeUpdate();

                if (filas > 0) {
                    JOptionPane.showMessageDialog(this, "promocion eliminada correctamente.");
                    limpiarCampos();
                    habilitarCampos(false);
                    modo = null;
                } else {
                    JOptionPane.showMessageDialog(this, "No se pudo eliminar el la promocion.", "Error", JOptionPane.ERROR_MESSAGE);
                }

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Error al eliminar promocion: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "opcion solo para administradores");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed
        if (modo == null) {
            JOptionPane.showMessageDialog(this, "Seleccione primero si es un registro nuevo o edición.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // --- Validaciones ---
        if (txtDescripcion.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar la descripción de la promoción.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (txtTipo.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar el tipo de promoción.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (txtCondicion.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar la condición de horas.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            int condicion = Integer.parseInt(txtCondicion.getText().trim());
            if (condicion <= 0) {
                JOptionPane.showMessageDialog(this, "La condición de horas debe ser mayor que 0.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // --- MODO NUEVO ---
            if (modo.equalsIgnoreCase("nuevo")) {
                CallableStatement cs = conexion.prepareCall("{call registrarPromocion(?, ?, ?)}");
                cs.setString(1, txtDescripcion.getText().trim());
                cs.setString(2, txtTipo.getText().trim());
                cs.setInt(3, condicion);
                cs.execute();

                JOptionPane.showMessageDialog(this, "Promoción registrada correctamente.");
                limpiarCampos();
                habilitarCampos(false);
                modo = null;

                // --- MODO EDICIÓN ---
            } else if (modo.equalsIgnoreCase("edicion")) {
                String sql = "UPDATE Promocion SET descripcion=?, tipo=?, condicionHoras=? WHERE idPromocion=?";
                PreparedStatement ps = conexion.prepareStatement(sql);
                ps.setString(1, txtDescripcion.getText().trim());
                ps.setString(2, txtTipo.getText().trim());
                ps.setInt(3, condicion);
                ps.setString(4, txtId.getText().trim());

                int filas = ps.executeUpdate();
                if (filas > 0) {
                    JOptionPane.showMessageDialog(this, "Promoción actualizada correctamente.");
                    limpiarCampos();
                    habilitarCampos(false);
                    modo = null;
                } else {
                    JOptionPane.showMessageDialog(this, "No se encontró una promoción con el ID especificado.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Ingrese un número válido en condición de horas.", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al guardar la promoción: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGrabarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGrabar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnVerPromos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCondicion;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables
}
