/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package igu;

import java.awt.BorderLayout;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author rafae
 */
public class PanelMantenimiento extends javax.swing.JPanel {
    private Connection conexion;
    private String usuario;
    private String nivel;
    /**
     * Creates new form PanelMantenimiento
     */
    public PanelMantenimiento(Connection conexion, String usuario, String nivel) {
        initComponents();
        PanelDegradado fondo = new PanelDegradado();

// MUY IMPORTANTE: dejar layout por defecto (BorderLayout)
        fondo.setLayout(new java.awt.BorderLayout());

// Pasar jPanel1 dentro del panel degradado
        PanelMant.setOpaque(false);
        fondo.add(PanelMant, BorderLayout.CENTER);

// Ahora reemplazas en el contenedor padre
        remove(PanelMant);
        add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 500));

// refrescar
        revalidate();
        repaint();

        this.conexion = conexion;
        this.usuario=usuario;
        this.nivel=nivel;
        personalizarBotones();
        
    }

    private void personalizarBotones() {
        java.awt.Font fuente = new java.awt.Font("Segoe UI Emoji", java.awt.Font.PLAIN, 13);

        btnGestionarTuristas.setFont(fuente);
        btnGestionarTuristas.setText("🧍‍♂️ GESTIONAR TURISTAS");

        btnGestionarRecursos.setFont(fuente);
        btnGestionarRecursos.setText("🛞 GESTIONAR RECURSOS");

        btnGestionarPromos.setFont(fuente);
        btnGestionarPromos.setText("🎟️ GESTIONAR PROMOCIONES");

        btnGestionarUsuarios.setFont(fuente);
        btnGestionarUsuarios.setText("👥 GESTIONAR USUARIOS");

        btnGestionarNiv.setFont(fuente);
        btnGestionarNiv.setText("📈 GESTIONAR NIVELES");
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelMant = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnGestionarTuristas = new javax.swing.JButton();
        btnGestionarRecursos = new javax.swing.JButton();
        btnGestionarPromos = new javax.swing.JButton();
        btnGestionarUsuarios = new javax.swing.JButton();
        btnGestionarNiv = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));
        setPreferredSize(new java.awt.Dimension(640, 500));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelMant.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BIENVENIDO AL PANEL DE MANTENIMIENTO");

        btnGestionarTuristas.setText("Gestionar Turistas");
        btnGestionarTuristas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarTuristasActionPerformed(evt);
            }
        });

        btnGestionarRecursos.setText("GestionarRecursos");
        btnGestionarRecursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarRecursosActionPerformed(evt);
            }
        });

        btnGestionarPromos.setText("jButton1");
        btnGestionarPromos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarPromosActionPerformed(evt);
            }
        });

        btnGestionarUsuarios.setText("jButton1");
        btnGestionarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarUsuariosActionPerformed(evt);
            }
        });

        btnGestionarNiv.setText("jButton1");
        btnGestionarNiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarNivActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelMantLayout = new javax.swing.GroupLayout(PanelMant);
        PanelMant.setLayout(PanelMantLayout);
        PanelMantLayout.setHorizontalGroup(
            PanelMantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelMantLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(PanelMantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGestionarTuristas, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                    .addComponent(btnGestionarPromos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addGroup(PanelMantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGestionarRecursos, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGestionarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
            .addGroup(PanelMantLayout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(btnGestionarNiv, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelMantLayout.setVerticalGroup(
            PanelMantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMantLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(91, 91, 91)
                .addGroup(PanelMantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGestionarTuristas)
                    .addComponent(btnGestionarRecursos))
                .addGap(32, 32, 32)
                .addGroup(PanelMantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGestionarPromos)
                    .addComponent(btnGestionarUsuarios))
                .addGap(62, 62, 62)
                .addComponent(btnGestionarNiv)
                .addContainerGap(178, Short.MAX_VALUE))
        );

        add(PanelMant, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 500));
    }// </editor-fold>//GEN-END:initComponents

    private void btnGestionarTuristasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarTuristasActionPerformed
          PanelGestionarTurista panelTuristas = new PanelGestionarTurista(conexion,nivel);
        showPanelMant(panelTuristas);
    }//GEN-LAST:event_btnGestionarTuristasActionPerformed

    private void btnGestionarPromosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarPromosActionPerformed
          PanelPromociones p = new PanelPromociones(conexion, nivel);
        showPanelMant(p);
    }//GEN-LAST:event_btnGestionarPromosActionPerformed

    private void btnGestionarRecursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarRecursosActionPerformed
          PanelRecursos2 pRecurso = new PanelRecursos2(conexion,nivel);
        showPanelMant(pRecurso);
    }//GEN-LAST:event_btnGestionarRecursosActionPerformed

    private void btnGestionarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarUsuariosActionPerformed
          if (nivel.equalsIgnoreCase("administrador")) {
            PanelGestionarUsuarios p = new PanelGestionarUsuarios(conexion, nivel);
            showPanelMant(p);
        }else{
            JOptionPane.showMessageDialog(null,"opcion solo para administrador");
        }
    }//GEN-LAST:event_btnGestionarUsuariosActionPerformed

    private void btnGestionarNivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarNivActionPerformed
        if (nivel.equalsIgnoreCase("administrador")) {
            PanelNiveles p = new PanelNiveles(conexion);
            showPanelMant(p);
        }else{
            JOptionPane.showMessageDialog(null,"opcion solo para administrador");
        }
    }//GEN-LAST:event_btnGestionarNivActionPerformed
    void showPanelMant(JPanel p){
        p.setSize(640, 500);
        p.setLocation(0, 0);
        PanelMant.removeAll();
        PanelMant.add(p);
        PanelMant.revalidate();
        PanelMant.repaint();
    
    
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelMant;
    private javax.swing.JButton btnGestionarNiv;
    private javax.swing.JButton btnGestionarPromos;
    private javax.swing.JButton btnGestionarRecursos;
    private javax.swing.JButton btnGestionarTuristas;
    private javax.swing.JButton btnGestionarUsuarios;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
