/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package igu;

import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author rafae
 */
public class PanelMantenimiento extends javax.swing.JPanel {
    private Connection conexion;
    private String usuario;
    private String nivel;
    /**
     * Creates new form PanelMantenimiento
     */
    public PanelMantenimiento(Connection conexion,String usuario,String nivel) {
        initComponents();
        this.conexion = conexion;
        this.usuario=usuario;
        this.nivel=nivel;
        personalizarBotones();
        
    }

    private void personalizarBotones() {
        java.awt.Font fuente = new java.awt.Font("Segoe UI Emoji", java.awt.Font.PLAIN, 13);

        btnGestionarTuristas.setFont(fuente);
        btnGestionarTuristas.setText("🧍‍♂️ GESTIONAR TURISTAS");

        btnGestionarRecursos.setFont(fuente);
        btnGestionarRecursos.setText("🛞 GESTIONAR RECURSOS");

        btnGestionarPromos.setFont(fuente);
        btnGestionarPromos.setText("🎟️ GESTIONAR PROMOCIONES");

        jButton1.setFont(fuente);
        jButton1.setText("👥 GESTIONAR USUARIOS");

        btnGestionarNiv.setFont(fuente);
        btnGestionarNiv.setText("📈 GESTIONAR NIVELES");
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelMant = new javax.swing.JPanel();
        subPanelMant = new javax.swing.JPanel();
        lblSaludoMantenimiento = new javax.swing.JLabel();
        btnGestionarTuristas = new javax.swing.JButton();
        btnGestionarRecursos = new javax.swing.JButton();
        btnGestionarPromos = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnGestionarNiv = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));
        setPreferredSize(new java.awt.Dimension(640, 500));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelMant.setBackground(new java.awt.Color(255, 255, 255));

        subPanelMant.setBackground(new java.awt.Color(255, 255, 255));

        lblSaludoMantenimiento.setForeground(new java.awt.Color(0, 0, 0));
        lblSaludoMantenimiento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSaludoMantenimiento.setText("          BIENVENIDO A MANTENIMIENTO DE DATOS");

        btnGestionarTuristas.setText("GESTIONAR TURISTAS");
        btnGestionarTuristas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGestionarTuristas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarTuristasActionPerformed(evt);
            }
        });

        btnGestionarRecursos.setText("GESTIONAR RECURSOS");
        btnGestionarRecursos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGestionarRecursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarRecursosActionPerformed(evt);
            }
        });

        btnGestionarPromos.setText("GESTIONAR PROMOCIONES");
        btnGestionarPromos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGestionarPromos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarPromosActionPerformed(evt);
            }
        });

        jButton1.setText("GESTIONAR USUARIOS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnGestionarNiv.setText("GESTIONAR NIVELES");
        btnGestionarNiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarNivActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout subPanelMantLayout = new javax.swing.GroupLayout(subPanelMant);
        subPanelMant.setLayout(subPanelMantLayout);
        subPanelMantLayout.setHorizontalGroup(
            subPanelMantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSaludoMantenimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, subPanelMantLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(subPanelMantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGestionarTuristas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGestionarPromos, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(subPanelMantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGestionarRecursos, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25))
            .addGroup(subPanelMantLayout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(btnGestionarNiv, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(221, Short.MAX_VALUE))
        );
        subPanelMantLayout.setVerticalGroup(
            subPanelMantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subPanelMantLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblSaludoMantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(subPanelMantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGestionarTuristas)
                    .addComponent(btnGestionarRecursos))
                .addGap(42, 42, 42)
                .addGroup(subPanelMantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGestionarPromos)
                    .addComponent(jButton1))
                .addGap(52, 52, 52)
                .addComponent(btnGestionarNiv)
                .addContainerGap(198, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelMantLayout = new javax.swing.GroupLayout(PanelMant);
        PanelMant.setLayout(PanelMantLayout);
        PanelMantLayout.setHorizontalGroup(
            PanelMantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(subPanelMant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelMantLayout.setVerticalGroup(
            PanelMantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(subPanelMant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        add(PanelMant, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 500));
    }// </editor-fold>//GEN-END:initComponents
    void showPanelMant(JPanel p){
        p.setSize(640, 500);
        p.setLocation(0, 0);
        PanelMant.removeAll();
         PanelMant.setLayout(null);    //
        PanelMant.add(p);
        PanelMant.revalidate();
        PanelMant.repaint();
    
    
    }
    private void btnGestionarTuristasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarTuristasActionPerformed
     PanelGestionarTurista panelTuristas = new PanelGestionarTurista(conexion,nivel);
     showPanelMant(panelTuristas);
   
    }//GEN-LAST:event_btnGestionarTuristasActionPerformed

    private void btnGestionarRecursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarRecursosActionPerformed
     PanelRecursos2 pRecurso = new PanelRecursos2(conexion,nivel);
        showPanelMant(pRecurso);
    }//GEN-LAST:event_btnGestionarRecursosActionPerformed

    private void btnGestionarPromosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarPromosActionPerformed
        PanelPromociones p = new PanelPromociones(conexion, nivel);
        showPanelMant(p);
    }//GEN-LAST:event_btnGestionarPromosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (nivel.equalsIgnoreCase("administrador")) {
            PanelGestionarUsuarios p = new PanelGestionarUsuarios(conexion, nivel);
            showPanelMant(p);
        }else{
            JOptionPane.showMessageDialog(null,"opcion solo para administrador");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnGestionarNivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarNivActionPerformed
           if (nivel.equalsIgnoreCase("administrador")) {
            PanelNiveles p = new PanelNiveles(conexion);
            showPanelMant(p);
        }else{
            JOptionPane.showMessageDialog(null,"opcion solo para administrador");
        }
    }//GEN-LAST:event_btnGestionarNivActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelMant;
    private javax.swing.JButton btnGestionarNiv;
    private javax.swing.JButton btnGestionarPromos;
    private javax.swing.JButton btnGestionarRecursos;
    private javax.swing.JButton btnGestionarTuristas;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblSaludoMantenimiento;
    private javax.swing.JPanel subPanelMant;
    // End of variables declaration//GEN-END:variables
}
