/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package igu;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author rafae
 */
public class PanelGestionarUsuarios extends javax.swing.JPanel {
    private Connection conexion;
    private String nivel;
    private String modo;
    /**
     * Creates new form PanelGestionarUsuarios
     */
    public PanelGestionarUsuarios(Connection conexion,String nivel) {
        initComponents();
        this.conexion=conexion;
        this.nivel=nivel;
        habilitarCampos(false);
        cargarNiveles();
        limpiarCampos();
    }
    private void limpiarCampos() {

        txtIdUsuario.setText("");
        txtUserName.setText("");
        txtCorreo.setText("");
        txtContraseña.setText("");
        jDateChooserFecha.setDate(null);
        jComboBoxNiveles.setSelectedIndex(-1);
       

    }
    


    private void habilitarCampos(boolean habilitar) {
        txtIdUsuario.setEditable(false);
        txtUserName.setEditable(habilitar);
        txtCorreo.setEditable(habilitar);
        txtContraseña.setEditable(habilitar);
       
        // DateChooser
        jDateChooserFecha.setEnabled(habilitar);

        // ComboBoxes
        jComboBoxNiveles.setEditable(habilitar);
        
    }


     private void cargarNiveles() {
        jComboBoxNiveles.removeAllItems();

        String sql = "SELECT NombreNivel FROM Nivel";
        try (PreparedStatement ps = conexion.prepareStatement(sql); ResultSet rs = ps.executeQuery()) {

            while (rs.next()) {
                // Solo añadimos la descripción, como "10%", "20%", etc.
                jComboBoxNiveles.addItem(rs.getString("NombreNivel"));
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al cargar promociones: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        txtIdUsuario = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtContraseña = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxNiveles = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jDateChooserFecha = new com.toedter.calendar.JDateChooser();
        jSeparator1 = new javax.swing.JSeparator();
        btnNuevo = new javax.swing.JButton();
        btnBuscarUsuario = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnGrabar = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BIENVENIDO AL MANTENIMIENTO DE USUARIOS DEL SISTEMA");

        jLabel2.setText("id Usuario");

        jLabel3.setText("Nombre de Usuario");

        jLabel4.setText("Correo");

        jLabel5.setText("contraseña");

        jLabel6.setText("Nivel");

        jComboBoxNiveles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setText("fecha de creacion");

        btnNuevo.setText("nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnBuscarUsuario.setText("buscar");
        btnBuscarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarUsuarioActionPerformed(evt);
            }
        });

        btnEditar.setText("editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setText("eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnGrabar.setText("grabar");
        btnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtIdUsuario)
                                    .addComponent(txtUserName)
                                    .addComponent(txtCorreo)
                                    .addComponent(txtContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE))
                                .addGap(33, 33, 33)
                                .addComponent(btnBuscarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jDateChooserFecha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                .addComponent(jComboBoxNiveles, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btnGrabar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtIdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscarUsuario)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBoxNiveles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jDateChooserFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo)
                    .addComponent(btnEditar)
                    .addComponent(btnEliminar)
                    .addComponent(btnGrabar))
                .addContainerGap(108, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 500));
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        limpiarCampos();
        habilitarCampos(true);
        modo = "nuevo";
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnBuscarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarUsuarioActionPerformed
        // Pedir el ID de usuario al usuario mediante JOptionPane
        String id = JOptionPane.showInputDialog(this, "Ingrese el ID del usuario a buscar (Ejemplo: U001):");

        // Si el usuario canceló o no ingresó nada
        if (id == null || id.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Búsqueda cancelada o vacía.");
            return;
        }

        id = id.trim().toUpperCase(); // Normalizamos el formato del ID
        limpiarCampos();

        String sql = "SELECT * FROM ActorUsuario WHERE idUsuario = ?";
        try (PreparedStatement ps = conexion.prepareStatement(sql)) {
            ps.setString(1, id);
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                // Mostrar los datos del usuario encontrado
                txtIdUsuario.setText(rs.getString("idUsuario"));
                txtUserName.setText(rs.getString("nameUsuario"));
                txtCorreo.setText(rs.getString("correo"));
                txtContraseña.setText(rs.getString("contraseña"));
                jDateChooserFecha.setDate(rs.getDate("fechaRegistro"));

                // Buscar y seleccionar el nombre del nivel correspondiente
                String idNivel = rs.getString("idNivel");
                PreparedStatement psNivel = conexion.prepareStatement(
                        "SELECT nombreNivel FROM Nivel WHERE idNivel = ?");
                psNivel.setString(1, idNivel);
                ResultSet rsN = psNivel.executeQuery();
                if (rsN.next()) {
                    jComboBoxNiveles.setSelectedItem(rsN.getString("nombreNivel"));
                }

                JOptionPane.showMessageDialog(this, "Usuario encontrado correctamente.");
                habilitarCampos(false);
                modo = "consulta";
            } else {
                JOptionPane.showMessageDialog(this, "No se encontró ningún usuario con el ID: " + id);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al buscar usuario: " + e.getMessage());
        }
    }//GEN-LAST:event_btnBuscarUsuarioActionPerformed
    
    private boolean esCorreoValido(String correo) {
        // Expresión regular para correos comunes (sin símbolos raros)
        String patronCorreo = "^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$";
        return correo.matches(patronCorreo);
    }

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if (txtIdUsuario.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Primero busque un usuario para editar.");
            return;
        }
        habilitarCampos(true);
        modo = "edicion";
        JOptionPane.showMessageDialog(null,"modo edicion activado ");
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
          String id = txtIdUsuario.getText().trim();
        if (id.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese o busque un usuario para eliminar.");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this, "¿Eliminar este usuario?", "Confirmar", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) return;

        String sql = "DELETE FROM ActorUsuario WHERE idUsuario = ?";
        try (PreparedStatement ps = conexion.prepareStatement(sql)) {
            ps.setString(1, id);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Usuario eliminado correctamente.");
            limpiarCampos();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al eliminar usuario: " + e.getMessage());
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed
        // === Validación de campos ===
        String nombre = txtUserName.getText().trim();
        String correo = txtCorreo.getText().trim();
        String pass = txtContraseña.getText().trim();
        java.util.Date fecha = jDateChooserFecha.getDate();
        String nivelSel = (String) jComboBoxNiveles.getSelectedItem();

        if (nombre.isEmpty() || correo.isEmpty() || pass.isEmpty() || fecha == null || nivelSel == null) {
            JOptionPane.showMessageDialog(this, "Complete todos los campos antes de grabar.", "Campos incompletos", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // === Validar formato de correo ===
        if (!esCorreoValido(correo)) {
            JOptionPane.showMessageDialog(this,
                    "Ingrese un correo válido.\nEjemplo: usuario@dominio.com",
                    "Formato de correo incorrecto",
                    JOptionPane.WARNING_MESSAGE);
            txtCorreo.requestFocus();
            return;
        }

        try {
            // === Obtener idNivel según nombre ===
            String idNivel = null;
            try (PreparedStatement psNivel = conexion.prepareStatement(
                    "SELECT idNivel FROM Nivel WHERE nombreNivel = ?")) {
                psNivel.setString(1, nivelSel);
                try (ResultSet rs = psNivel.executeQuery()) {
                    if (rs.next()) {
                        idNivel = rs.getString("idNivel");
                    } else {
                        JOptionPane.showMessageDialog(this, "El nivel seleccionado no existe en la base de datos.");
                        return;
                    }
                }
            }

            // === Lógica según modo ===
            if ("nuevo".equalsIgnoreCase(modo)) {
                // ======= MODO NUEVO: usa el SP registrarUsuario =======
                try (java.sql.CallableStatement cs = conexion.prepareCall("{ call dbo.registrarUsuario(?, ?, ?, ?, ?, ?) }")) {
                    cs.setString(1, nombre);
                    cs.setString(2, correo);
                    cs.setString(3, pass);
                    cs.setDate(4, new java.sql.Date(fecha.getTime()));
                    cs.setString(5, idNivel);
                    cs.registerOutParameter(6, java.sql.Types.CHAR);
                    cs.execute();

                    String nuevoId = cs.getString(6);
                    txtIdUsuario.setText(nuevoId); // lo mostramos en pantalla
                    JOptionPane.showMessageDialog(this, "Usuario registrado correctamente con ID: " + nuevoId);
                }

            } else if ("edicion".equalsIgnoreCase(modo)) {
                // ======= MODO EDITAR: actualiza con UPDATE =======
                String sql = "UPDATE ActorUsuario SET nameUsuario=?, correo=?, contraseña=?, fechaRegistro=?, idNivel=? WHERE idUsuario=?";
                try (PreparedStatement ps = conexion.prepareStatement(sql)) {
                    ps.setString(1, nombre);
                    ps.setString(2, correo);
                    ps.setString(3, pass);
                    ps.setDate(4, new java.sql.Date(fecha.getTime()));
                    ps.setString(5, idNivel);
                    ps.setString(6, txtIdUsuario.getText().trim());
                    int filas = ps.executeUpdate();

                    if (filas > 0) {
                        JOptionPane.showMessageDialog(this, "Usuario actualizado correctamente.");
                    } else {
                        JOptionPane.showMessageDialog(this, "No se encontró el usuario para actualizar.", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                }

            } else {
                JOptionPane.showMessageDialog(this, "Seleccione primero 'Nuevo' o 'Editar' antes de grabar.", "Modo no definido", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // === Post-operación ===
            habilitarCampos(false);
            modo = "";

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al grabar usuario: " + e.getMessage(), "Error SQL", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGrabarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarUsuario;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGrabar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox<String> jComboBoxNiveles;
    private com.toedter.calendar.JDateChooser jDateChooserFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtContraseña;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtIdUsuario;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
