/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package igu;

/**
 *
 * @author rafae
 */
public class PanelEntrada extends javax.swing.JPanel {
    private String saludo;
    /**
     * Creates new form PanelEntrada
     */
    public PanelEntrada(String saludo) {
        initComponents();
        // 1. TRANSPARENCIA TOTAL
        // Hacemos que este panel y el jPanel1 sean invisibles para ver el degradado de fondo
        this.setOpaque(false);
        jPanel1.setOpaque(false);

        // 2. FORMATEO DEL TEXTO (Mayúsculas)
        // Convertimos "juanperez" a "JUANPEREZ" para que se vea importante
        String nombreUsuario = (saludo != null) ? saludo.toUpperCase() : "USUARIO";

        // 3. FUENTE MODERNA
        // Cambiamos DialogInput por Segoe UI, más grande y en Negrita
        jLabel1.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 32));

        // 4. COLOR CORPORATIVO (Azul Petróleo)
        // Usamos el mismo color del menú lateral para consistencia
        jLabel1.setForeground(new java.awt.Color(31, 78, 95));

        // 5. MENSAJE FINAL
        jLabel1.setText("¡HOLA, " + nombreUsuario + "!");

        // Ajuste extra: Asegurarnos que el texto esté centrado verticalmente en su espacio
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelSaludo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 110));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabelSaludo.setForeground(new java.awt.Color(0, 0, 0));
        jLabelSaludo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelSaludo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/unnamed (1).jpg"))); // NOI18N
        jLabelSaludo.setText("BIENVENIDO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabelSaludo, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelSaludo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 500));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelSaludo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
