/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package igu;

import java.awt.BorderLayout;
import java.math.BigDecimal;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author rafae
 */
public class PanelPagos extends javax.swing.JPanel {

    private Connection conexion;
    private String modo;
    private String idUsuario;

    /**
     * Creates new form PanelPagos
     */
    public PanelPagos(Connection conexion, String idUsuario) {
        initComponents();

        PanelDegradado fondo = new PanelDegradado();

// MUY IMPORTANTE: dejar layout por defecto (BorderLayout)
        fondo.setLayout(new java.awt.BorderLayout());

// Pasar jPanel1 dentro del panel degradado
        jPanel1.setOpaque(false);
        fondo.add(jPanel1, BorderLayout.CENTER);

// Ahora reemplazas en el contenedor padre
        remove(jPanel1);
        add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 500));

// refrescar
        revalidate();
        repaint();
        this.idUsuario = idUsuario;
        this.conexion = conexion;
        habilitarCampos(false);
        txtIgv.setEditable(false);
        txtIgv.setText("0.00");

        // 🟢 Calcular IGV y total automáticamente al escribir
        txtMontoSinIgv.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyReleased(java.awt.event.KeyEvent evt) {
                calcularMontos();
            }
        });
        cargarUltimoAlquiler();

    }

    private void cargarUltimoAlquiler() {

        String sql = """
        SELECT TOP 1
            a.idAlquiler,
            t.dni,
            a.total
        FROM Alquiler a
        JOIN Turista t ON a.idTurista = t.idTurista
        WHERE a.idUsuario = ?
          AND NOT EXISTS (
              SELECT 1
              FROM Pago p
              WHERE p.idAlquiler = a.idAlquiler
          )
        ORDER BY a.fechaInicio DESC
    """;

        try (PreparedStatement ps = conexion.prepareStatement(sql)) {

            ps.setString(1, idUsuario);
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {

                txtIdAlquiler.setText(rs.getString("idAlquiler"));
                txtDniTuri.setText(rs.getString("dni"));
                txtMontoSinIgv.setText(rs.getBigDecimal("total").toString());

                calcularMontos();

                JcmbMetodoPago.setSelectedIndex(0);
                JcmbEstadoPago.setSelectedItem("Pendiente");

            } else {
                JOptionPane.showMessageDialog(this,
                        "No hay alquileres pendientes de pago",
                        "Información",
                        JOptionPane.INFORMATION_MESSAGE
                );
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                    "Error al cargar alquiler pendiente: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
        habilitarCampos(true);
        modo="nuevo";
    }


 

    private void limpiarCampos() {
        txtIdPago.setText("");
        txtIdAlquiler.setText("");
        txtDniTuri.setText("");
        jDateChooserFechaPago.setDate(null);
        txtMontoSinIgv.setText("");
        txtIgv.setText("");
        txtMontoTotal.setText("");
        JcmbMetodoPago.setSelectedIndex(0);
        JcmbEstadoPago.setSelectedIndex(0);
        
    }
    
    private void habilitarCampos(boolean estado) {
        txtIdAlquiler.setEditable(false);
        txtIdPago.setEditable(false);
        txtDniTuri.setEditable(false);
        btnBuscarAlquiller.setEnabled(estado);
        jDateChooserFechaPago.setEnabled(estado);
        txtMontoTotal.setEditable(false);
        JcmbMetodoPago.setEnabled(estado);
        JcmbEstadoPago.setEnabled(false);
        txtMontoSinIgv.setEditable(false);
        
       
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIdAlquiler = new javax.swing.JTextField();
        btnBuscarAlquiller = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtDniTuri = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtMontoTotal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jDateChooserFechaPago = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        JcmbMetodoPago = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtIdPago = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        JcmbEstadoPago = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        btnNuevo = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnGrabar = new javax.swing.JButton();
        btnPagar = new javax.swing.JButton();
        btnAnular = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtMontoSinIgv = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtIgv = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bienvenido a pagos");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("id Alquiler");

        btnBuscarAlquiller.setText("buscar");
        btnBuscarAlquiller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarAlquillerActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Dni Turista");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Monto a pagar");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("fecha de pago");

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Metodo de pago");

        JcmbMetodoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "efectivo", "yape", "plin", "tarjeta" }));

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("id Pago");

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("estado del pago");

        JcmbEstadoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pendiente", "Completado", "anulado" }));

        btnNuevo.setText("nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnBuscar.setText("buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnEditar.setText("editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setText("eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnGrabar.setText("grabar");
        btnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarActionPerformed(evt);
            }
        });

        btnPagar.setText("Pagar");
        btnPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarActionPerformed(evt);
            }
        });

        btnAnular.setText("Anular");
        btnAnular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnularActionPerformed(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("monto sin igv");

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("igv");

        txtIgv.setText("18%");
        txtIgv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIgvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(JcmbEstadoPago, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(JcmbMetodoPago, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel7))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtIdAlquiler)
                                            .addComponent(txtIdPago, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(119, 119, 119)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(btnPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnAnular, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(btnBuscarAlquiller, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(38, 38, 38)
                                                .addComponent(jLabel3))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGap(97, 97, 97)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)))))
                                        .addGap(29, 29, 29)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtIgv)
                                            .addComponent(txtDniTuri, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jDateChooserFechaPago, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                                            .addComponent(txtMontoSinIgv)
                                            .addComponent(txtMontoTotal))))
                                .addGap(0, 63, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnGrabar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtIdAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscarAlquiller)
                        .addComponent(jLabel3)
                        .addComponent(txtDniTuri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel7)
                        .addComponent(txtIdPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jDateChooserFechaPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(JcmbMetodoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtMontoSinIgv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIgv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(JcmbEstadoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtMontoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPagar)
                            .addComponent(btnAnular))
                        .addGap(18, 18, 18)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo)
                    .addComponent(btnBuscar)
                    .addComponent(btnEditar)
                    .addComponent(btnEliminar)
                    .addComponent(btnGrabar))
                .addContainerGap(152, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 500));
    }// </editor-fold>//GEN-END:initComponents

    private void seleccionarItemIgnoreCase(JComboBox<String> combo, String valorBD) {
        if (valorBD == null) {
            return;
        }
        for (int i = 0; i < combo.getItemCount(); i++) {
            String item = combo.getItemAt(i);
            if (item.equalsIgnoreCase(valorBD)) {
                combo.setSelectedIndex(i);
                return;
            }
        }
        // Si no encontró coincidencia exacta, puedes dejar el primero o limpiar
        combo.setSelectedIndex(0);
    }

    
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String idPago = JOptionPane.showInputDialog(this, "Ingrese el ID del pago (ej. P001):");
        if (idPago == null || idPago.trim().isEmpty()) {
            return;
        }

        String sql = """
        SELECT p.idPago, p.idAlquiler, p.fechaPago, p.monto, p.metodoPago, p.estado,
               t.dni
        FROM Pago p
        JOIN Alquiler a ON p.idAlquiler = a.idAlquiler
        JOIN Turista t ON a.idTurista = t.idTurista
        WHERE p.idPago = ?
    """;

        try (PreparedStatement ps = conexion.prepareStatement(sql)) {
            ps.setString(1, idPago);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    txtIdPago.setText(rs.getString("idPago"));
                    txtIdAlquiler.setText(rs.getString("idAlquiler"));
                    jDateChooserFechaPago.setDate(rs.getDate("fechaPago"));
                    txtMontoSinIgv.setText(String.valueOf(rs.getBigDecimal("monto")));
                    seleccionarItemIgnoreCase(JcmbMetodoPago, rs.getString("metodoPago"));
                    seleccionarItemIgnoreCase(JcmbEstadoPago, rs.getString("estado"));

                    txtDniTuri.setText(rs.getString("dni")); // 🟢 ahora sí carga el DNI

                    btnAnular.setEnabled(true);
                    habilitarCampos(false);
                    calcularMontos();
                    
                    JOptionPane.showMessageDialog(this, "✅ Pago encontrado correctamente.");
                } else {
                    JOptionPane.showMessageDialog(this, "No se encontró ningún pago con ese ID.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al buscar pago: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        limpiarCampos();
        habilitarCampos(true);
        btnAnular.setEnabled(false);
        modo = "nuevo";
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnBuscarAlquillerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarAlquillerActionPerformed
        String idAlquiler = JOptionPane.showInputDialog(this, "Ingrese el ID del alquiler (ej. A001):");
        if (idAlquiler == null || idAlquiler.trim().isEmpty()) return;

        String sql = "SELECT a.idTurista, t.dni, a.total FROM Alquiler a JOIN Turista t ON a.idTurista = t.idTurista WHERE a.idAlquiler = ?";
        try (PreparedStatement ps = conexion.prepareStatement(sql)) {
            ps.setString(1, idAlquiler);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    txtIdAlquiler.setText(idAlquiler);
                    txtDniTuri.setText(rs.getString("dni"));
                    txtMontoSinIgv.setText(String.valueOf(rs.getBigDecimal("total")));
                    calcularMontos();
                } else {
                    JOptionPane.showMessageDialog(this, "No se encontró el alquiler indicado.", "Aviso", JOptionPane.WARNING_MESSAGE);
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al buscar alquiler: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    
    }//GEN-LAST:event_btnBuscarAlquillerActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
         if (txtIdPago.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe buscar un pago antes de editar.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        modo = "edicion";
        habilitarCampos(true);
        btnBuscarAlquiller.setEnabled(false);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
        try {
            if (modo != null && modo.equals("nuevo")) {
                // 🔹 Solo mueve el combo visualmente
                JcmbEstadoPago.setSelectedItem("Completado");
                JOptionPane.showMessageDialog(this,
                        "✅ El estado se marcó como 'Completado'.\nGrabe para registrar el pago.",
                        "Modo nuevo", JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            if (modo != null && modo.equals("edicion")) {
                String idPago = txtIdPago.getText().trim();
                if (idPago.isEmpty()) {
                    JOptionPane.showMessageDialog(this,
                            "Debe buscar un pago antes de marcarlo como completado.",
                            "Advertencia", JOptionPane.WARNING_MESSAGE);
                    return;
                }

                String sql = "UPDATE Pago SET estado = 'Completado' WHERE idPago = ?";
                try (PreparedStatement ps = conexion.prepareStatement(sql)) {
                    ps.setString(1, idPago);
                    int filas = ps.executeUpdate();
                    if (filas > 0) {
                        JOptionPane.showMessageDialog(this,
                                "💰 Pago marcado como COMPLETADO exitosamente.",
                                "Éxito", JOptionPane.INFORMATION_MESSAGE);
                        JcmbEstadoPago.setSelectedItem("Completado");
                    } else {
                        JOptionPane.showMessageDialog(this,
                                "No se encontró el pago especificado.",
                                "Error", JOptionPane.ERROR_MESSAGE);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this,
                        "Debe estar en modo 'nuevo' o 'edición' para usar esta función.",
                        "Modo inválido", JOptionPane.WARNING_MESSAGE);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                    "Error al actualizar estado: " + e.getMessage(),
                    "Error SQL", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnPagarActionPerformed

    private void btnAnularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnularActionPerformed
        try {
            if (modo != null && modo.equals("nuevo")) {
                // 🔹 Solo cambia el combo visualmente
                seleccionarItemIgnoreCase(JcmbEstadoPago, "anulado");
                JOptionPane.showMessageDialog(this,
                        "⚠️ Estado marcado como 'Anulado'.\nGrabe para registrar el cambio.",
                        "Modo nuevo", JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            if (modo != null && modo.equals("edicion")) {
                String idPago = txtIdPago.getText().trim();
                if (idPago.isEmpty()) {
                    JOptionPane.showMessageDialog(this,
                            "Debe buscar un pago antes de anularlo.",
                            "Advertencia", JOptionPane.WARNING_MESSAGE);
                    return;
                }

                int confirm = JOptionPane.showConfirmDialog(this,
                        "¿Está seguro de ANULAR este pago?",
                        "Confirmar anulación", JOptionPane.YES_NO_OPTION);

                if (confirm != JOptionPane.YES_OPTION) {
                    return;
                }

                String sql = "UPDATE Pago SET estado = 'Anulado' WHERE idPago = ?";
                try (PreparedStatement ps = conexion.prepareStatement(sql)) {
                    ps.setString(1, idPago);
                    int filas = ps.executeUpdate();
                    if (filas > 0) {
                        JOptionPane.showMessageDialog(this,
                                "🚫 Pago ANULADO correctamente.",
                                "Éxito", JOptionPane.INFORMATION_MESSAGE);
                         seleccionarItemIgnoreCase(JcmbEstadoPago, "anulado");
                    } else {
                        JOptionPane.showMessageDialog(this,
                                "No se encontró el pago especificado.",
                                "Error", JOptionPane.ERROR_MESSAGE);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this,
                        "Debe estar en modo 'nuevo' o 'edición' para usar esta función.",
                        "Modo inválido", JOptionPane.WARNING_MESSAGE);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                    "Error al anular pago: " + e.getMessage(),
                    "Error SQL", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAnularActionPerformed

    private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed
        if (modo == null || (!modo.equalsIgnoreCase("nuevo") && !modo.equalsIgnoreCase("edicion"))) {
            JOptionPane.showMessageDialog(this,
                    "Debe seleccionar primero 'Nuevo' o 'Editar' antes de grabar.",
                    "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            conexion.setAutoCommit(false);

            // 🟢 1️⃣ Obtener datos del formulario
            String idPago = txtIdPago.getText().trim();
            String idAlquiler = txtIdAlquiler.getText().trim();
            java.util.Date fechaSeleccionada = jDateChooserFechaPago.getDate();
            if (fechaSeleccionada == null) {
                JOptionPane.showMessageDialog(this, "Debe seleccionar una fecha de pago.", "Advertencia", JOptionPane.WARNING_MESSAGE);
                return;
            }
            java.sql.Date fechaPago = new java.sql.Date(fechaSeleccionada.getTime());

            String montoTexto = txtMontoSinIgv.getText().trim();
            if (montoTexto.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Debe ingresar un monto válido.", "Advertencia", JOptionPane.WARNING_MESSAGE);
                return;
            }

            BigDecimal monto = new BigDecimal(montoTexto);
            String metodoPago = JcmbMetodoPago.getSelectedItem().toString();
            String estado = JcmbEstadoPago.getSelectedItem().toString();

            // 🧾 2️⃣ SI ES NUEVO → usar procedimiento almacenado registrarPago
            if (modo.equalsIgnoreCase("nuevo")) {

                // 🔹 Verificar si el alquiler ya tiene un pago COMPLETADO
                String sqlVerificar = "SELECT estado FROM Pago WHERE idAlquiler = ?";
                try (PreparedStatement psVerificar = conexion.prepareStatement(sqlVerificar)) {
                    psVerificar.setString(1, idAlquiler);
                    ResultSet rsVerificar = psVerificar.executeQuery();

                    while (rsVerificar.next()) {
                        String estadoExistente = rsVerificar.getString("estado");
                        if (estadoExistente.equalsIgnoreCase("Completado")) {
                            JOptionPane.showMessageDialog(this,
                                    "⚠️ Este alquiler (" + idAlquiler + ") ya tiene un pago COMPLETADO.\n"
                                    + "No se puede registrar otro pago para él.",
                                    "Pago duplicado", JOptionPane.WARNING_MESSAGE);
                            conexion.rollback();
                            return;
                        }
                    }
                }

                // 🔹 Ejecutar SP registrarPago
                String sql = "{call registrarPago(?,?,?,?,?)}";
                try (CallableStatement cs = conexion.prepareCall(sql)) {
                    cs.setString(1, idAlquiler);
                    cs.setDate(2, fechaPago);
                    cs.setBigDecimal(3, monto);
                    cs.setString(4, metodoPago);
                    cs.setString(5, estado);
                    cs.execute();
                }

                // 🔹 Recuperar último ID generado
                String sqlUltimo = "SELECT TOP 1 idPago FROM Pago ORDER BY idPago DESC";
                try (PreparedStatement ps = conexion.prepareStatement(sqlUltimo); ResultSet rs = ps.executeQuery()) {
                    if (rs.next()) {
                        txtIdPago.setText(rs.getString("idPago"));
                    }
                }

                JOptionPane.showMessageDialog(this, "✅ Pago registrado correctamente.");

                // ✏️ 3️⃣ SI ES EDICIÓN → actualizar pago existente
            } else if (modo.equalsIgnoreCase("edicion")) {
                if (idPago.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Debe buscar un pago antes de editarlo.", "Advertencia", JOptionPane.WARNING_MESSAGE);
                    return;
                }

                String sqlUpdate = """
                UPDATE Pago
                SET idAlquiler = ?, fechaPago = ?, monto = ?, metodoPago = ?, estado = ?
                WHERE idPago = ?
            """;
                try (PreparedStatement ps = conexion.prepareStatement(sqlUpdate)) {
                    ps.setString(1, idAlquiler);
                    ps.setDate(2, fechaPago);
                    ps.setBigDecimal(3, monto);
                    ps.setString(4, metodoPago);
                    ps.setString(5, estado);
                    ps.setString(6, idPago);
                    ps.executeUpdate();
                }

                JOptionPane.showMessageDialog(this, "✅ Pago actualizado correctamente.");
            }

            // 🧩 4️⃣ Finalizar transacción
            conexion.commit();
            modo = null;
            habilitarCampos(false);

        } catch (Exception e) {
            try {
                conexion.rollback();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Error al revertir cambios: " + ex.getMessage());
            }
            JOptionPane.showMessageDialog(this, "❌ Error al grabar pago: " + e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            try {
                conexion.setAutoCommit(true);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Error al restaurar conexión: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnGrabarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        String idPago = txtIdPago.getText().trim();

        if (idPago.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Debe buscar o seleccionar un pago antes de eliminar.",
                    "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int opcion = JOptionPane.showConfirmDialog(this,
                "¿Está seguro de eliminar el pago " + idPago + "?",
                "Confirmar eliminación", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

        if (opcion != JOptionPane.YES_OPTION) {
            return;
        }

        try {
            String sql = "DELETE FROM Pago WHERE idPago = ?";
            try (PreparedStatement ps = conexion.prepareStatement(sql)) {
                ps.setString(1, idPago);
                int filas = ps.executeUpdate();

                if (filas > 0) {
                    JOptionPane.showMessageDialog(this,
                            "✅ Pago eliminado correctamente.",
                            "Eliminado", JOptionPane.INFORMATION_MESSAGE);
                    limpiarCampos();
                    habilitarCampos(false);
                } else {
                    JOptionPane.showMessageDialog(this,
                            "⚠️ No se encontró el pago especificado.",
                            "Aviso", JOptionPane.WARNING_MESSAGE);
                }
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                    "❌ Error al eliminar el pago: " + e.getMessage(),
                    "Error SQL", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtIgvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIgvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIgvActionPerformed

    // 🧮 Método para calcular IGV y monto total
    private void calcularMontos() {
        try {
            String textoSinIgv = txtMontoSinIgv.getText().trim();

            // Si el campo está vacío, limpiar los otros
            if (textoSinIgv.isEmpty()) {
                txtIgv.setText("0.00");
                txtMontoTotal.setText("0.00");
                return;
            }

            // Monto sin IGV
            BigDecimal montoSinIgv = new BigDecimal(textoSinIgv);

            // IGV fijo (según BD)
            BigDecimal igvPorcentaje = BigDecimal.valueOf(0.18);
            BigDecimal montoIGV = montoSinIgv.multiply(igvPorcentaje);
            BigDecimal montoConIGV = montoSinIgv.add(montoIGV);

            // Mostrar con 2 decimales
            txtIgv.setText(montoIGV.setScale(2, BigDecimal.ROUND_HALF_UP).toString());
            txtMontoTotal.setText(montoConIGV.setScale(2, BigDecimal.ROUND_HALF_UP).toString());

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                    "⚠️ Ingrese un monto válido (solo números y punto decimal).",
                    "Error de formato", JOptionPane.WARNING_MESSAGE);
            txtIgv.setText("0.00");
            txtMontoTotal.setText("0.00");
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JcmbEstadoPago;
    private javax.swing.JComboBox<String> JcmbMetodoPago;
    private javax.swing.JButton btnAnular;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscarAlquiller;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGrabar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnPagar;
    private com.toedter.calendar.JDateChooser jDateChooserFechaPago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtDniTuri;
    private javax.swing.JTextField txtIdAlquiler;
    private javax.swing.JTextField txtIdPago;
    private javax.swing.JTextField txtIgv;
    private javax.swing.JTextField txtMontoSinIgv;
    private javax.swing.JTextField txtMontoTotal;
    // End of variables declaration//GEN-END:variables
}
