/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package igu;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author rafae
 */
public class PanelRecursos2 extends javax.swing.JPanel {
    private Connection conexion;
    private String nivel;
    private String modo;
    /**
     * Creates new form PanelRecursos2
     */
    public PanelRecursos2(Connection conexion, String nivel) {
        initComponents();
        this.conexion = conexion;
        this.nivel = nivel;
        habilitarCampos(false);
        // 🔹 Corrige desplazamiento visual por márgenes del GroupLayout:
        bg.setBorder(null);
        bg.setBounds(0, 0, 640, 500);
        setBounds(0, 0, 640, 500);
        setOpaque(false);
        bg.setOpaque(true);

    }

    private void limpiarCampos() {
        txtId.setText("");
        txtTipo.setText("");
        txtAreaDescrip.setText("");
        txtTarifa.setText("");
        txtEstado.setText("");
        txtUbi.setText("");
        txtCant.setText("");
    }

    private void habilitarCampos(boolean habilitar) {
        txtId.setEnabled(habilitar);
        txtTipo.setEnabled(habilitar);
        txtAreaDescrip.setEnabled(habilitar);
        txtTarifa.setEnabled(habilitar);
        txtEstado.setEnabled(habilitar);
        txtUbi.setEnabled(habilitar);
        txtCant.setEnabled(habilitar);
    }

    private void buscarRecurso(String idBuscar) {
        if (idBuscar == null || idBuscar.trim().isEmpty()) {
            return;
        }

        try {
            String sql = "SELECT * FROM Recursos WHERE idRecursos = ?";
            PreparedStatement ps = conexion.prepareStatement(sql);
            ps.setString(1, idBuscar.trim());
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                txtId.setText(rs.getString("idRecursos"));
                txtTipo.setText(rs.getString("tipo"));
                txtAreaDescrip.setText(rs.getString("descripcion"));
                txtTarifa.setText(rs.getString("tarifaHora"));
                txtEstado.setText(rs.getString("estado"));
                txtUbi.setText(rs.getString("ubicacion"));
                txtCant.setText(rs.getString("cantidad"));
                habilitarCampos(false);
               

                JOptionPane.showMessageDialog(this, "Recurso encontrado. Ahora puede editarlo.");
            } else {
                JOptionPane.showMessageDialog(this, "No se encontró un recurso con ese ID.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al buscar recurso: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        lblDescrip = new javax.swing.JLabel();
        lblTarifa = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        lblUbi = new javax.swing.JLabel();
        lblCant = new javax.swing.JLabel();
        txtTipo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaDescrip = new javax.swing.JTextArea();
        txtTarifa = new javax.swing.JTextField();
        txtEstado = new javax.swing.JTextField();
        txtUbi = new javax.swing.JTextField();
        txtCant = new javax.swing.JTextField();
        btnNuevo = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnGrabar = new javax.swing.JButton();
        btnVer = new javax.swing.JButton();
        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BIENVENIDO A LA GESTION DE RECURSOS");
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 280, -1));

        lblTipo.setForeground(new java.awt.Color(0, 0, 0));
        lblTipo.setText("Tipo");
        bg.add(lblTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 76, 93, -1));

        lblDescrip.setForeground(new java.awt.Color(0, 0, 0));
        lblDescrip.setText("Descripcion");
        bg.add(lblDescrip, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 114, 93, -1));

        lblTarifa.setForeground(new java.awt.Color(0, 0, 0));
        lblTarifa.setText("Tarifa hora");
        bg.add(lblTarifa, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 177, 93, -1));

        lblEstado.setForeground(new java.awt.Color(0, 0, 0));
        lblEstado.setText("Estado");
        bg.add(lblEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 227, 93, -1));

        lblUbi.setForeground(new java.awt.Color(0, 0, 0));
        lblUbi.setText("Ubicacion");
        bg.add(lblUbi, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 273, 93, -1));

        lblCant.setForeground(new java.awt.Color(0, 0, 0));
        lblCant.setText("cantidad");
        bg.add(lblCant, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 315, 93, -1));
        bg.add(txtTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 72, 387, -1));

        txtAreaDescrip.setColumns(20);
        txtAreaDescrip.setRows(5);
        jScrollPane1.setViewportView(txtAreaDescrip);

        bg.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 114, 387, 41));

        txtTarifa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTarifaActionPerformed(evt);
            }
        });
        bg.add(txtTarifa, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 177, 387, -1));
        bg.add(txtEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 223, 387, -1));
        bg.add(txtUbi, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 269, 387, -1));
        bg.add(txtCant, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 315, 387, -1));

        btnNuevo.setText("Nuevo");
        btnNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        bg.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 80, -1));

        btnBuscar.setText("buscar");
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        bg.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 90, -1));

        btnEditar.setText("Editar");
        btnEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        bg.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 90, -1));

        btnEliminar.setText("Eliminar");
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        bg.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 370, 100, -1));

        btnGrabar.setText("Grabar");
        btnGrabar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarActionPerformed(evt);
            }
        });
        bg.add(btnGrabar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, 120, -1));

        btnVer.setText("ver recursos");
        btnVer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerActionPerformed(evt);
            }
        });
        bg.add(btnVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 450, 140, 30));

        lblId.setForeground(new java.awt.Color(0, 0, 0));
        lblId.setText("Id");
        bg.add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 42, -1, -1));
        bg.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 38, 387, -1));

        add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 500));
    }// </editor-fold>//GEN-END:initComponents

    private void txtTarifaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTarifaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTarifaActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
      if(nivel.equalsIgnoreCase("administrador")){
          txtId.setEnabled(false);
       limpiarCampos();
       modo="nuevo";
        habilitarCampos(true);
      }else{
          JOptionPane.showMessageDialog(null, "opcion solo para administradores");
      }
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String recursoBuscado = javax.swing.JOptionPane.showInputDialog(this, "Ingrese el ID del recurso a buscar (ej: R001)");
        if (recursoBuscado != null) {
            buscarRecurso(recursoBuscado.trim());
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if (nivel.equalsIgnoreCase("administrador")) {
            habilitarCampos(true);
           txtId.setEnabled(false);
        modo = "edicion";
        }else{
            JOptionPane.showMessageDialog(null, "opcion solo para administradores");
        }
        
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (nivel.equalsIgnoreCase("administrador")) {

            String idEliminar = JOptionPane.showInputDialog(this, "Ingrese el ID del recurso a eliminar (ej: R001):");

            // Validar entrada
            if (idEliminar == null || idEliminar.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Debe ingresar un ID de recurso válido.", "Advertencia", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Confirmación
            int confirmar = JOptionPane.showConfirmDialog(this,
                    "¿Está seguro que desea eliminar el recurso con ID " + idEliminar + "?",
                    "Confirmar eliminación",
                    JOptionPane.YES_NO_OPTION);

            if (confirmar != JOptionPane.YES_OPTION) {
                return; // usuario canceló
            }

            try {
                // Verificar si existe el recurso antes de eliminarlo
                String sqlCheck = "SELECT COUNT(*) FROM Recursos WHERE idRecursos = ?";
                PreparedStatement psCheck = conexion.prepareStatement(sqlCheck);
                psCheck.setString(1, idEliminar.trim());
                ResultSet rs = psCheck.executeQuery();
                rs.next();
                int count = rs.getInt(1);

                if (count == 0) {
                    JOptionPane.showMessageDialog(this, "No existe ningún recurso con el ID especificado.", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                // Eliminar registro
                String sqlDelete = "DELETE FROM Recursos WHERE idRecursos = ?";
                PreparedStatement psDelete = conexion.prepareStatement(sqlDelete);
                psDelete.setString(1, idEliminar.trim());
                int filas = psDelete.executeUpdate();

                if (filas > 0) {
                    JOptionPane.showMessageDialog(this, "Recurso eliminado correctamente.");
                    limpiarCampos();
                    habilitarCampos(false);
                    modo = null;
                } else {
                    JOptionPane.showMessageDialog(this, "No se pudo eliminar el recurso.", "Error", JOptionPane.ERROR_MESSAGE);
                }

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Error al eliminar recurso: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "opcion solo para administradores");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed
        if (modo == null) {
            JOptionPane.showMessageDialog(this, "Seleccione primero si es un registro nuevo o edición.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // --- Validaciones ---
        if (txtTipo.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar el tipo del recurso.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (txtTarifa.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar la tarifa por hora.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (txtCant.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar la cantidad.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            double tarifa = Double.parseDouble(txtTarifa.getText().trim());
            int cantidad = Integer.parseInt(txtCant.getText().trim());

            if (tarifa <= 0) {
                JOptionPane.showMessageDialog(this, "La tarifa debe ser mayor que 0.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (cantidad <= 0) {
                JOptionPane.showMessageDialog(this, "La cantidad debe ser mayor que 0.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (modo.equals("nuevo")) {
                // Procedimiento almacenado para registrar
                CallableStatement cs = conexion.prepareCall("{call registrarRecurso(?, ?, ?, ?, ?, ?)}");
                cs.setString(1, txtTipo.getText().trim());
                cs.setString(2, txtAreaDescrip.getText().trim());
                cs.setBigDecimal(3, new java.math.BigDecimal(tarifa));
                cs.setString(4, txtEstado.getText().trim().isEmpty() ? "Disponible" : txtEstado.getText().trim());
                cs.setString(5, txtUbi.getText().trim());
                cs.setInt(6, cantidad);
                cs.execute();

                JOptionPane.showMessageDialog(this, "Recurso registrado correctamente.");
                limpiarCampos();
                habilitarCampos(false);

            } else if (modo.equals("edicion")) {
                // Aquí puedes hacer un UPDATE
                String sql = "UPDATE Recursos SET tipo=?, descripcion=?, tarifaHora=?, estado=?, ubicacion=?, cantidad=? WHERE idRecursos=?";
                PreparedStatement ps = conexion.prepareStatement(sql);
                ps.setString(1, txtTipo.getText().trim());
                ps.setString(2, txtAreaDescrip.getText().trim());
                ps.setBigDecimal(3, new java.math.BigDecimal(tarifa));
                ps.setString(4, txtEstado.getText().trim());
                ps.setString(5, txtUbi.getText().trim());
                ps.setInt(6, cantidad);
                ps.setString(7, txtId.getText().trim()); // suponiendo que tienes txtBuscar para ID
                int filas = ps.executeUpdate();

                if (filas > 0) {
                    JOptionPane.showMessageDialog(this, "Recurso actualizado correctamente.");
                    limpiarCampos();
                    habilitarCampos(false);
                } else {
                    JOptionPane.showMessageDialog(this, "No se encontró ningún recurso con el ID especificado.", "Error", JOptionPane.ERROR_MESSAGE);
                }

            }

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Error: asegúrese de ingresar valores numéricos válidos en tarifa y cantidad.", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al guardar recurso: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGrabarActionPerformed

    private void btnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActionPerformed
        ventanaRecursos v=new ventanaRecursos(conexion);
        v.setVisible(true);
        v.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnVerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGrabar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnVer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCant;
    private javax.swing.JLabel lblDescrip;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblTarifa;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblUbi;
    private javax.swing.JTextArea txtAreaDescrip;
    private javax.swing.JTextField txtCant;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtTarifa;
    private javax.swing.JTextField txtTipo;
    private javax.swing.JTextField txtUbi;
    // End of variables declaration//GEN-END:variables
}
