/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package igu;

import java.sql.Connection;

/**
 *
 * @author rafae
 */
public class PanelGestionarTurista extends javax.swing.JPanel {
    private Connection conexion;
    private String modo;
    private String nivel;
    /**
     * Creates new form GestionarTurista
     */
    private void limpiarCampos() {
        txtNombre.setText("");
        txtApellidos.setText("");
        txtDni.setText("");
        txtNacionalidad.setText("");
        txtContacto.setText("");
    }
    public PanelGestionarTurista(Connection conexion,String nivel) {
        this.conexion= conexion;
        initComponents();
        habilitarCampos(false);
        this.nivel=nivel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnNuevoTurista = new javax.swing.JButton();
        btnBuscarturista = new javax.swing.JButton();
        btnEditarTurista = new javax.swing.JButton();
        btnEliminaTurista = new javax.swing.JButton();
        btnGuardarTurista = new javax.swing.JButton();
        lblNombre = new javax.swing.JLabel();
        lblApellidos = new javax.swing.JLabel();
        lblDni = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblNacionalidad = new javax.swing.JLabel();
        lblContacto = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        txtDni = new javax.swing.JTextField();
        txtNacionalidad = new javax.swing.JTextField();
        txtContacto = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BIENVENIDO A LA GESTION DE TURISTAS");

        btnNuevoTurista.setText("nuevo");
        btnNuevoTurista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoTuristaActionPerformed(evt);
            }
        });

        btnBuscarturista.setText("buscar");
        btnBuscarturista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarturistaActionPerformed(evt);
            }
        });

        btnEditarTurista.setText("editar");
        btnEditarTurista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarTuristaActionPerformed(evt);
            }
        });

        btnEliminaTurista.setText("eliminar");
        btnEliminaTurista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminaTuristaActionPerformed(evt);
            }
        });

        btnGuardarTurista.setText("guardar");
        btnGuardarTurista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarTuristaActionPerformed(evt);
            }
        });

        lblNombre.setForeground(new java.awt.Color(0, 0, 0));
        lblNombre.setText("Nombre ");

        lblApellidos.setForeground(new java.awt.Color(0, 0, 0));
        lblApellidos.setText("Apellidos");

        lblDni.setForeground(new java.awt.Color(0, 0, 0));
        lblDni.setText("DNI");

        txtNombre.setBackground(new java.awt.Color(255, 255, 255));
        txtNombre.setForeground(new java.awt.Color(0, 0, 0));

        lblNacionalidad.setForeground(new java.awt.Color(0, 0, 0));
        lblNacionalidad.setText("nacionalidad");

        lblContacto.setForeground(new java.awt.Color(0, 0, 0));
        lblContacto.setText("contacto");

        txtApellidos.setBackground(new java.awt.Color(255, 255, 255));
        txtApellidos.setForeground(new java.awt.Color(0, 0, 0));
        txtApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidosActionPerformed(evt);
            }
        });

        txtDni.setBackground(new java.awt.Color(255, 255, 255));
        txtDni.setForeground(new java.awt.Color(0, 0, 0));

        txtNacionalidad.setBackground(new java.awt.Color(255, 255, 255));
        txtNacionalidad.setForeground(new java.awt.Color(0, 0, 0));

        txtContacto.setBackground(new java.awt.Color(255, 255, 255));
        txtContacto.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblApellidos)
                                            .addComponent(lblNombre)
                                            .addComponent(lblDni))
                                        .addGap(19, 19, 19))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblNacionalidad)
                                        .addComponent(lblContacto)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtApellidos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDni, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtContacto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNacionalidad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(btnNuevoTurista, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(btnBuscarturista, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditarTurista, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminaTurista, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnGuardarTurista, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellidos)
                    .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDni)
                    .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNacionalidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblContacto))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevoTurista)
                    .addComponent(btnBuscarturista)
                    .addComponent(btnEditarTurista)
                    .addComponent(btnEliminaTurista)
                    .addComponent(btnGuardarTurista))
                .addGap(183, 183, 183))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 500));
    }// </editor-fold>//GEN-END:initComponents
    // 🔹 Habilita o deshabilita los campos del formulario

    private void habilitarCampos(boolean habilitar) {
        txtNombre.setEditable(habilitar);
        txtApellidos.setEditable(habilitar);
        txtDni.setEditable(habilitar);
        txtNacionalidad.setEditable(habilitar);
        txtContacto.setEditable(habilitar);
    }

    private void buscarTuristaPorDni(String dniBuscado) {
    if (dniBuscado.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Debe ingresar un DNI para buscar.");
        return;
    }
    
    String sql = "SELECT * FROM Turista WHERE dni = ?";
    try (java.sql.PreparedStatement ps = conexion.prepareStatement(sql)) {
        ps.setString(1, dniBuscado);
        try (java.sql.ResultSet rs = ps.executeQuery()) {
            if (rs.next()) {
                // 🔹 Rellenar los campos con los datos encontrados
                txtNombre.setText(rs.getString("nombre"));
                txtApellidos.setText(rs.getString("apellidos"));
                txtDni.setText(rs.getString("dni"));
                txtNacionalidad.setText(rs.getString("nacionalidad"));
                txtContacto.setText(rs.getString("contacto"));
                
                habilitarCampos(false);
                
                javax.swing.JOptionPane.showMessageDialog(this, "Turista encontrado.");
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "No se encontró ningún turista con ese DNI.");
                limpiarCampos();
            }
        }
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error al buscar turista: " + e.getMessage());
    }
}

    private void btnBuscarturistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarturistaActionPerformed
        String dniBuscado = javax.swing.JOptionPane.showInputDialog(this, "Ingrese el DNI del turista a buscar:");
        if (dniBuscado != null) {
            buscarTuristaPorDni(dniBuscado.trim());
        }
    }//GEN-LAST:event_btnBuscarturistaActionPerformed

    private void btnEditarTuristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarTuristaActionPerformed
        habilitarCampos(true);
        modo = "edicion";
    }//GEN-LAST:event_btnEditarTuristaActionPerformed

    private void txtApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidosActionPerformed

    private void btnNuevoTuristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoTuristaActionPerformed
       limpiarCampos();
       modo="nuevo";
        habilitarCampos(true);
    }//GEN-LAST:event_btnNuevoTuristaActionPerformed

    private void btnGuardarTuristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarTuristaActionPerformed
        // 1️⃣ Validar que se haya elegido un modo
        if (modo == null || modo.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debe seleccionar una acción: Nuevo o Editar");
            return;
        }

        // 2️⃣ Capturar los valores del formulario
        String nombre = txtNombre.getText().trim();
        String apellidos = txtApellidos.getText().trim();
        String dni = txtDni.getText().trim();
        String nacionalidad = txtNacionalidad.getText().trim();
        String contacto = txtContacto.getText().trim();

        // 3️⃣ Validar campos obligatorios
        if (nombre.isEmpty() || apellidos.isEmpty() || dni.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debe completar al menos Nombre, Apellidos y DNI.");
            return;
        }

        // 4️⃣ Ejecutar acción según el modo
        if (modo.equals("edicion")) {
            // 🔹 UPDATE (editar)
            String sql = "UPDATE Turista SET nombre=?, apellidos=?, nacionalidad=?, contacto=? WHERE dni=?";
            try (java.sql.PreparedStatement ps = conexion.prepareStatement(sql)) {
                ps.setString(1, nombre);
                ps.setString(2, apellidos);
                ps.setString(3, nacionalidad);
                ps.setString(4, contacto);
                ps.setString(5, dni);

                int filas = ps.executeUpdate();
                if (filas > 0) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Turista actualizado correctamente.");
                    limpiarCampos();
                    habilitarCampos(false);
                    modo = "";
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "No se encontró un turista con ese DNI.");
                }

            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Error al actualizar turista: " + e.getMessage());
            }

        } else if (modo.equals("nuevo")) {
            // 🔹 INSERT mediante procedimiento almacenado registrarTurista
            try (java.sql.CallableStatement cs = conexion.prepareCall("{CALL registrarTurista(?, ?, ?, ?, ?)}")) {
                cs.setString(1, nombre);
                cs.setString(2, apellidos);
                cs.setString(3, dni);
                cs.setString(4, nacionalidad.isEmpty() ? null : nacionalidad);
                cs.setString(5, contacto.isEmpty() ? null : contacto);

                cs.execute();
                javax.swing.JOptionPane.showMessageDialog(this, "Turista registrado correctamente mediante SP.");

                limpiarCampos();
                habilitarCampos(false);
                modo = "";

            } catch (java.sql.SQLIntegrityConstraintViolationException e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Ya existe un turista con ese DNI.");
            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Error al registrar turista: " + e.getMessage());
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Modo desconocido: " + modo);
        }
    }//GEN-LAST:event_btnGuardarTuristaActionPerformed

    private void btnEliminaTuristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminaTuristaActionPerformed
        if (nivel.equalsIgnoreCase("administrador")) {

            String dni = txtDni.getText().trim();

            if (dni.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Debe ingresar o buscar un turista para eliminar.");
                return;
            }

            int confirmacion = javax.swing.JOptionPane.showConfirmDialog(
                    this,
                    "¿Está seguro de eliminar al turista con DNI " + dni + "?",
                    "Confirmar eliminación",
                    javax.swing.JOptionPane.YES_NO_OPTION
            );

            if (confirmacion == javax.swing.JOptionPane.YES_OPTION) {
                String sql = "DELETE FROM Turista WHERE dni = ?";
                try (java.sql.PreparedStatement ps = conexion.prepareStatement(sql)) {
                    ps.setString(1, dni);
                    int filas = ps.executeUpdate();

                    if (filas > 0) {
                        javax.swing.JOptionPane.showMessageDialog(this, "Turista eliminado correctamente.");
                        limpiarCampos();
                        habilitarCampos(false);
                        modo = "";
                    } else {
                        javax.swing.JOptionPane.showMessageDialog(this, "No se encontró un turista con ese DNI.");
                    }
                } catch (Exception e) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Error al eliminar turista: " + e.getMessage());
                }
            }
        }
    }//GEN-LAST:event_btnEliminaTuristaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarturista;
    private javax.swing.JButton btnEditarTurista;
    private javax.swing.JButton btnEliminaTurista;
    private javax.swing.JButton btnGuardarTurista;
    private javax.swing.JButton btnNuevoTurista;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblContacto;
    private javax.swing.JLabel lblDni;
    private javax.swing.JLabel lblNacionalidad;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtContacto;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtNacionalidad;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
