/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package igu;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rafae
 */
public class VentanaAlquileres extends javax.swing.JFrame {
    private Connection conexion;
    /**
     * Creates new form VentanaAlquileres
     */
    public VentanaAlquileres(Connection conexion) {
        initComponents();
        this.conexion = conexion;
        // En el GroupLayout o AbsoluteLayout
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 500));
        setSize(900, 550);

        jTable1.setDefaultEditor(Object.class, null);
        jTable1.getTableHeader().setReorderingAllowed(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "idAlquiler", "idTurista", "DNI Turista", "Nombre Turista",
                    "fechaInicio", "horaInicio", "Duracion", "Total",
                    "estado", "idPromocion", "idUsuario", "horaFinal"
                }
        ));
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(60);   // idAlquiler
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(60);   // idTurista
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(80);   // DNI
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(160);  // Nombre
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(90);   // fecha
        jTable1.getColumnModel().getColumn(5).setPreferredWidth(70);   // horaInicio
        jTable1.getColumnModel().getColumn(6).setPreferredWidth(60);   // duracion
        jTable1.getColumnModel().getColumn(7).setPreferredWidth(70);   // total
        jTable1.getColumnModel().getColumn(8).setPreferredWidth(90);   // estado
        jTable1.getColumnModel().getColumn(9).setPreferredWidth(80);   // promo
        jTable1.getColumnModel().getColumn(10).setPreferredWidth(70);  // usuario
        jTable1.getColumnModel().getColumn(11).setPreferredWidth(70);  //
        cargarAlquileres();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    private void cargarAlquileres() {
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setRowCount(0); // limpiar filas anteriores

        String sql = """
        SELECT 
            A.idAlquiler, 
            A.idTurista, 
            ISNULL(T.DNI, '—') AS DNI,
            ISNULL(CONCAT(T.nombre, ' ', T.apellidos), '—') AS NombreCompleto,
            A.fechaInicio, 
            A.horaInicio, 
            A.Duracion, 
            A.total, 
            A.estado, 
            ISNULL(A.idPromocion, '—') AS idPromocion,
            A.idUsuario, 
            ISNULL(CONVERT(VARCHAR(8), A.horaFinal, 108), '—') AS horaFinal
        FROM Alquiler A
        LEFT JOIN Turista T ON A.idTurista = T.idTurista
        ORDER BY A.idAlquiler
    """;

        try (PreparedStatement ps = conexion.prepareStatement(sql); ResultSet rs = ps.executeQuery()) {

            while (rs.next()) {
                Object[] fila = new Object[12];
                fila[0] = rs.getString("idAlquiler");
                fila[1] = rs.getString("idTurista");
                fila[2] = rs.getString("DNI");
                fila[3] = rs.getString("NombreCompleto");
                fila[4] = rs.getDate("fechaInicio");
                fila[5] = rs.getString("horaInicio");
                fila[6] = rs.getInt("Duracion");
                fila[7] = rs.getBigDecimal("total");
                fila[8] = rs.getString("estado");
                fila[9] = rs.getString("idPromocion");
                fila[10] = rs.getString("idUsuario");
                fila[11] = rs.getString("horaFinal");
                modelo.addRow(fila);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                    "Error al cargar los alquileres: " + e.getMessage(),
                    "Error SQL", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idAlquiler", "idTurista", "fechaInicio", "horaInicio", "Duracion", "Total", "estado", "idPromocion", "idUsuario", "horaFinal"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 781, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
